Repository stablekernel/protoc-gen-go-mcp, pull requests merged in 2025-05, with the labels that each got.

#68 feat: Improve comment processing
  cmd/protoc-gen-go-mcp/mcp.go
  examples/gen/example/v1/example.pb.go
  examples/gen/example/v1/example_grpc.pb.go
  examples/gen/example/v1/example_mcp.pb.go
  examples/protos/example.proto
Labels: feat

#65 feat: Add GitHub Actions workflow for build and release process
  .github/workflows/build-release.yml
  .github/workflows/build.yml
  .github/workflows/release-please.yml
  .gitignore
  .goreleaser.yaml
  .release-please-manifest.json
  release-please-config.json
Labels: feat

#76 fix: Update README.md
  README.md
Labels: documentation, fix

#78 fix: Update .release-please-manifest.json
  .release-please-manifest.json
Labels: fix

#80 fix: release please token
  .github/workflows/release-please.yml
Labels: fix

#71 chore: Improve type casting in generateFieldAssignment
  cmd/protoc-gen-go-mcp/mcp.go
  cmd/protoc-gen-go-mcp/mcp_test.go
  examples/gen/example/v1/example.pb.go
  examples/gen/example/v1/example_mcp.pb.go
Labels: chore
